/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Yen' at '10/26/16 8:50 PM' with Gradle 3.1
 *
 * @author Yen, @date 10/26/16 8:50 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
